# Site settings
title: qqzh002's Blog
email: qqzh002@gmail.com
description: >
  qqzh002's Blog
baseurl: ""
url: "http://qqzh002.github.io"
github_username: qqzh002

# Build settings
markdown: kramdown
